# Generated by Django 3.1.7 on 2021-04-03 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='اسم القسم')),
                ('slug', models.SlugField(blank=True, help_text='يتم انشائه تلقائيا', max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='انشئ في')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='حدث في')),
            ],
            options={
                'verbose_name': 'القسم',
                'verbose_name_plural': 'الاقسام',
                'ordering': ('-updated_at',),
                'index_together': {('id', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ShopInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='اسم المتجر')),
                ('image', models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='شعار المتجر')),
                ('phone', models.CharField(max_length=120, verbose_name='رقم الهاتف')),
                ('tax_num', models.CharField(max_length=120, verbose_name='الرقم الضريبي')),
            ],
            options={
                'verbose_name': 'اعدادات المتجر',
                'verbose_name_plural': 'اعدادات المتجر',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='اسم المنتج')),
                ('product_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='كود المنتج')),
                ('description', models.TextField(blank=True, verbose_name='تفاصيل المنتج')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('stock', models.PositiveIntegerField(verbose_name='الكمية المتاحة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='انشئ في')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
            ],
            options={
                'verbose_name': 'المنتج',
                'verbose_name_plural': 'المنتجات',
                'ordering': ('-created_at',),
            },
        ),
    ]
